name: ManHuntPlus
version: 1.0
author: tulXoro
main: me.tulXoro.manhuntPlus.ManHunt
api-version: 1.13

commands:
  hunter:
    description: Hunter commands.
  walls:
    description: Wall commands.
  freeforall:
    description: Freeforall commands.
  infiltration:
    description: Infiltrator commands.  